import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import "./globals.css";
import Sidebar from "./Layouts/Sidebar/Sidebar";
import NewRelease from "./Layouts/NewRelease/NewRelease";

const barlow = Barlow({ weight: ["400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${barlow.className} p-2 bg-black`}>
        <div className="grid grid-cols-6 gap-2">
          <div className="col-span-1 height-layout rounded-md">
            <Sidebar />
          </div>
          <div className="col-span-4 bg-page height-layout overflow-y-auto overflow-hidden rounded-md hidden-scrollbar">
            {children}
          </div>
          <div className="col-span-1 bg-new_release height-layout overflow-y-auto rounded-md hidden-scrollbar overflow-hidden">
            <NewRelease />
          </div>
        </div>
      </body>
    </html>
  );
}
